baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Gary Smith"
theme = "Stack"

[menu]
[[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = 10
    identifier = "home"
    [menu.main.params]
        icon = "home"
        newTab = false
[[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 10
    identifier = "resume"
    [menu.main.params]
        icon = "user"
        newTab = false