baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Smitty's Blog"
theme = "LoveIt"

# Author config
# 作者配置
[author]
  name = "Gary Smith"
  email = ""
  link = ""

# Menu config
# 菜单配置
[menu]
  [[menu.main]]
    weight = 1
    identifier = "guides"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Guides"
    url = "/guides/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""